#!/usr/bin/env python3
"""Master setup script for the IT Security Copilot Demo.

Verifies prerequisites, initializes the demo baseline, and pushes to GitHub.
"""
from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
from pathlib import Path

# ── ANSI color helpers ──────────────────────────────────────────────────────

RESET = "\033[0m"
BOLD = "\033[1m"
RED = "\033[91m"
GREEN = "\033[92m"
YELLOW = "\033[93m"
BLUE = "\033[94m"
CYAN = "\033[96m"


def info(msg: str) -> None:
    print(f"  {BLUE}ℹ{RESET}  {msg}")


def success(msg: str) -> None:
    print(f"  {GREEN}✔{RESET}  {msg}")


def warn(msg: str) -> None:
    print(f"  {YELLOW}⚠{RESET}  {msg}")


def error(msg: str) -> None:
    print(f"  {RED}✖{RESET}  {msg}")


def header(msg: str) -> None:
    print(f"\n{BOLD}{CYAN}{'─' * 60}{RESET}")
    print(f"{BOLD}{CYAN}  {msg}{RESET}")
    print(f"{BOLD}{CYAN}{'─' * 60}{RESET}\n")


def step(num: int, msg: str) -> None:
    print(f"\n  {BOLD}[{num}/7]{RESET} {msg}")


# ── Helpers ─────────────────────────────────────────────────────────────────

REPO_ROOT = Path(__file__).resolve().parent.parent
GITHUB_OWNER = "sautalwar"
GITHUB_REPO = "it-security-copilot-demo"


def run(cmd: list[str], *, check: bool = True, capture: bool = False) -> subprocess.CompletedProcess[str]:
    """Run a subprocess command with consistent options."""
    return subprocess.run(
        cmd,
        cwd=REPO_ROOT,
        check=check,
        capture_output=capture,
        text=True,
    )


def command_exists(name: str) -> bool:
    """Check if a command is available on PATH."""
    return shutil.which(name) is not None


# ── Steps ───────────────────────────────────────────────────────────────────


def verify_prerequisites() -> bool:
    """Step 1: Verify that git, gh CLI, and Python are available."""
    step(1, "Verifying prerequisites")

    all_ok = True

    # Git
    if command_exists("git"):
        result = run(["git", "--version"], capture=True, check=False)
        success(f"git found: {result.stdout.strip()}")
    else:
        error("git is not installed — https://git-scm.com/")
        all_ok = False

    # GitHub CLI
    if command_exists("gh"):
        result = run(["gh", "--version"], capture=True, check=False)
        version_line = result.stdout.strip().split("\n")[0]
        success(f"gh CLI found: {version_line}")
    else:
        error("GitHub CLI (gh) is not installed — https://cli.github.com/")
        all_ok = False

    # Python
    success(f"Python found: {sys.version.split()[0]}")

    if not all_ok:
        error("Please install missing prerequisites and try again.")
    return all_ok


def check_github_auth() -> bool:
    """Step 2: Check that the user is authenticated with gh CLI."""
    step(2, "Checking GitHub authentication")

    result = run(["gh", "auth", "status"], capture=True, check=False)
    output = result.stdout + result.stderr

    if result.returncode == 0:
        # Extract the logged-in account from output
        for line in output.splitlines():
            if "Logged in" in line or "account" in line.lower():
                success(line.strip())
                break
        else:
            success("GitHub CLI is authenticated")
        return True
    else:
        error("Not authenticated with GitHub CLI.")
        info("Run: gh auth login")
        return False


def create_env_file() -> None:
    """Step 3: Create a .env file with repo configuration."""
    step(3, "Creating .env configuration file")

    env_path = REPO_ROOT / ".env"
    env_content = (
        f"# IT Security Copilot Demo — generated by setup.py\n"
        f"GITHUB_OWNER={GITHUB_OWNER}\n"
        f"GITHUB_REPO={GITHUB_REPO}\n"
        f"DEMO_BASELINE_TAG=demo-baseline\n"
    )

    env_path.write_text(env_content, encoding="utf-8")
    success(f".env created at {env_path}")


def copy_baseline_files() -> None:
    """Step 4: Copy vulnerable baseline files into the working tree."""
    step(4, "Copying vulnerable baseline files into working tree")

    scenarios_dir = REPO_ROOT / "scenarios"
    if not scenarios_dir.exists():
        warn("No scenarios/ directory found — skipping baseline copy")
        return

    copied = 0
    for scenario_dir in sorted(scenarios_dir.iterdir()):
        if not scenario_dir.is_dir():
            continue

        baseline_dir = scenario_dir / "baseline"
        if not baseline_dir.exists():
            continue

        for src_file in baseline_dir.rglob("*"):
            if not src_file.is_file():
                continue

            # Determine destination: vulnerable-app/<relative-path>
            rel_path = src_file.relative_to(baseline_dir)
            dest = REPO_ROOT / "vulnerable-app" / rel_path
            dest.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src_file, dest)
            copied += 1

    if copied > 0:
        success(f"Copied {copied} baseline file(s) into vulnerable-app/")
    else:
        warn("No baseline files found in scenarios/*/baseline/")


def commit_baseline() -> None:
    """Step 5: Commit the baseline state and tag it."""
    step(5, "Committing baseline state")

    run(["git", "add", "-A"])

    # Check if there's anything to commit
    result = run(["git", "status", "--porcelain"], capture=True)
    if not result.stdout.strip():
        warn("Working tree is clean — nothing to commit")
    else:
        run(["git", "commit", "-m", "chore: initialize demo baseline"])
        success("Committed: chore: initialize demo baseline")

    # Tag the baseline
    run(["git", "tag", "-f", "demo-baseline"], check=False)
    success("Tagged current commit as 'demo-baseline'")


def push_to_github() -> None:
    """Step 6: Push the baseline to GitHub."""
    step(6, "Pushing baseline to GitHub")

    # Determine current branch
    result = run(["git", "branch", "--show-current"], capture=True)
    branch = result.stdout.strip() or "main"

    run(["git", "push", "-u", "origin", branch], check=False)
    run(["git", "push", "--tags", "-f"], check=False)
    success(f"Pushed branch '{branch}' and tags to origin")


def enable_actions() -> None:
    """Step 7: Enable GitHub Actions on the repository."""
    step(7, "Enabling GitHub Actions")

    result = run(
        ["gh", "api", f"repos/{GITHUB_OWNER}/{GITHUB_REPO}/actions/permissions",
         "-X", "PUT", "-f", "enabled=true", "-f", "allowed_actions=all"],
        capture=True,
        check=False,
    )

    if result.returncode == 0:
        success("GitHub Actions enabled on the repository")
    else:
        warn("Could not enable Actions via API (may already be enabled)")


def print_ready_message() -> None:
    """Print the final ready message with demo URL."""
    repo_url = f"https://github.com/{GITHUB_OWNER}/{GITHUB_REPO}"
    header("🎉  Demo Environment Ready!")
    print(f"  Repository : {BOLD}{repo_url}{RESET}")
    print(f"  Actions    : {repo_url}/actions")
    print(f"  Baseline   : tagged as {BOLD}demo-baseline{RESET}")
    print()
    print(f"  {GREEN}Next step:{RESET} Run {BOLD}python scripts/demo_runner.py{RESET} to start the demo")
    print()


# ── Main ────────────────────────────────────────────────────────────────────


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Set up the IT Security Copilot Demo environment.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="Example:\n  python scripts/setup.py\n",
    )
    parser.add_argument(
        "--skip-push",
        action="store_true",
        help="Skip pushing to GitHub (useful for local testing)",
    )
    args = parser.parse_args()

    header("🛡️  IT Security Copilot Demo — Setup")

    # Step 1: Prerequisites
    if not verify_prerequisites():
        sys.exit(1)

    # Step 2: GitHub auth
    if not args.skip_push and not check_github_auth():
        sys.exit(1)

    # Step 3: .env
    create_env_file()

    # Step 4: Baseline files
    copy_baseline_files()

    # Step 5: Commit
    commit_baseline()

    # Step 6: Push
    if args.skip_push:
        step(6, "Pushing baseline to GitHub")
        warn("Skipped (--skip-push)")
    else:
        push_to_github()

    # Step 7: Enable Actions
    if args.skip_push:
        step(7, "Enabling GitHub Actions")
        warn("Skipped (--skip-push)")
    else:
        enable_actions()

    # Done
    print_ready_message()


if __name__ == "__main__":
    main()
